Do full clones for now
- until fetch issue with some of http frontends are resolved (#2)

diff --git a/gitwatch b/gitwatch
--- a/gitwatch
+++ b/gitwatch
@@ -26,7 +26,7 @@ function die { echo "$@" 1>&2; exit 1; }
 
 if [ "$GW_CACHE" = "" ]; then GW_CACHE=~/.cache/gitwatch; fi
 
-GIT_DIR="$GW_CACHE/$(echo -n "$URL" | md5sum | tr -cd 'a-f0-9')"
+GIT_DIR="$GW_CACHE/$(echo -n "2:$URL" | md5sum | tr -cd 'a-f0-9')"
 OLD_COMMIT_PATH="$GIT_DIR/old-commit-$BRANCH"
 
 # Updating local cache
@@ -35,12 +35,10 @@ mkdir -p $(dirname "$GIT_DIR") || die "gw: failed to create cache dir"
 
 if [ -d "$GIT_DIR" ]
 then
-  unset DEPTH
   cd "$GIT_DIR" || die "gw: cannot cd to git dir"
-  git branch | grep -Pq '^[\s*]+'"$BRANCH"'$' 1>&2 || DEPTH='--depth=1'
-  git fetch $DEPTH origin "$BRANCH" 1>&2 || die "gw: git fetch failed"
+  git fetch origin "$BRANCH" 1>&2 || die "gw: git fetch failed"
 else
-  git clone --depth=1 --bare --branch "$BRANCH" \
+  git clone --single-branch --bare --branch "$BRANCH" \
     -c remote.origin.fetch='+refs/heads/*:refs/heads/*' \
     "$URL" "$GIT_DIR" 1>&2 || die "gw: git clone failed"
   git --git-dir="$GIT_DIR" show-ref -s "$BRANCH" > "$OLD_COMMIT_PATH" ||
